owenthereal/upterm

- ftests/test_client.go
- ftests/test_host.go
- host/internal/command.go
- host/internal/pty.go
- host/internal/server.go
Linux kernel return EIO when attempting to read from a master pseudo
terminal which no longer has an open slave. So ignore error here.
See https://github.com/creack/pty/issues/21
> Ignore pty path error on Linux

- server/server.go
- server/sshproxy.go
- server/sshproxy_test.go
- server/wsproxy.go
Requests to WebSocketProxy are routed to SSHProxy so that SSHProxy
always terminate ssh connection for a consistent authenticate machanism.
> WebSocketProxy routes to SSHProxy

- cmd/upterm/command/host.go
- ftests/client_test.go
- ftests/ftests_test.go
- host/host.go
- host/internal/server.go
This adds a read-only flag that allows hosting an upterm session that is read-only. Clients can connect as normal but won't be able to interact with the session. All other functionality remains as is, this simply doesn't attach the stdin of the client to the session pty.
> Add --read-only flag

- host/internal/event.go
When client drops with a `kill`, host reports the following errors due
to pty is closed:
```
ERRO[0015] error handling window changed                 error="error resizing window: bad file descriptor"
```
> Ignore bad file descriptor error when resizing window

- host/host.go
hostname and remote can be both IPs
> Remove duplicated address in `~/.ssh/known_hosts`

- cmd/uptermd/internal/command/root.go
- ftests/ftests_test.go
- ftests/host_test.go
- host/host.go
- host/internal/reversetunnel.go
- host/internal/server.go
- host/signer.go
- server/cert.go
- server/server.go
- server/sshd.go
- server/sshd_test.go
- server/sshproxy.go
- server/sshproxy_test.go
- server/sshrouting.go
- upterm/const.go
- utils/utils.go
Make use of public-key certificate authentication: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.certkeys. The followings are changed:
* Server returns a cert instead of a public key
* SSH proxy and upstream communicated using public-key cert auth, instead of converting to password auth
* Extending ssh cert with upterm extension for internal message passing.
* Host verifies cert from server
> Public-key Certificate Authentication

- cmd/upterm/command/host.go
- host/host.go
- host/signer.go
- host/signer_test.go
- utils/utils.go
Mark private key optional for `upterm host`.
Private key is first read from SSH Agent if no private key file is specified.
When there is not private key from SSH Agent or a file, a private key is generated.
Fixes https://github.com/owenthereal/upterm/issues/73.
> Make private key optional for `upterm host`

- go.mod
- go.sum
- vendor/golang.org/x/crypto/ssh/handshake.go
- vendor/golang.org/x/crypto/ssh/messages.go
- vendor/modules.txt
This adds signature algorithms are preffered order to be used for "publickey" auth.
It prefers ED25519 over RSA if clients have the keys.
See
https://github.com/owenthereal/upterm.crypto/commit/d2a67c5c7b65d18c49fed59726a82c6e9bd32192.
> Update a fork of x/crypto with RFC8308 support

- host/signer.go
- host/signer_test.go
Do not automatically add keys to SSH agent for `upterm host`. This should be the job of
`ssh-add`.
> Do not automatically add keys to SSH agent

- .github/workflows/build.yml
This should allow running the CI for https://github.com/owenthereal/upterm/pull/115.
> Allow running GitHub Actions for pull requests

- README.md
- cmd/upterm/command/host.go
- host/signer.go
This adds new flags to use a GitHub/GitLab's user public keys as
authorized keys. The keys are downloaded, processed and added to any
existing authorized keys provided by the --authorized-key flag.
This fixes #72.
> Add --github-user and --gitlab-user flags

- go.mod
- host/internal/server.go
- io/writer.go
- io/writer_test.go
Clients can see empty screen when they join the hosts. This buffers the last N bytes from the host and show to the clients when they first join.
> Buffer N bytes from the host and show to clients

- .dockerignore
- Dockerfile.uptermd
This PR bases the output Docker image on `SCRATCH` instead of alpine. Alpine is a great base, but for statically linked Go apps, we don't even need that.
I'm currently self-hosting using this updated image, it works identically as far as I can tell (e.g. no permission issues from the `noroot` user).
Sizes were calculated as:
```bash
docker build -f Dockerfile.uptermd -t uptermd .
docker save uptermd -o uptermd.tar
docker build -f Dockerfile.uptermd -t uptermd-new .
docker save uptermd-new -o uptermd-new.tar
```
`uptermd.tar` is ~26 MB, `uptermd-new.tar` is 21 MB.
The 5 MB isn't really _that_ important when the image is already only 26 MB (as compared to some enormous Docker image people sling around), but I figured, why not?
> Shrink uptermd Docker image by 5 MB, 20%

- .dockerignore
- Dockerfile.uptermd
This reverts commit bb763d6cdd9e5b1da00ffe794c71b3dfe0422828.
@bcspragu I have to revert https://github.com/owenthereal/upterm/pull/225 because the production community server shares the same image and needs `sh` to compute fly.io node address at boot time: https://github.com/owenthereal/upterm/blob/2e48f7341cf51a291bb626ddfc70ae56da0b49d0/fly.toml#L11-L12. I think we might have to stick with the Alpine image or if you have a suggestion that a smaller image that has a shell in it.
> Revert "Shrink uptermd Docker image by 5 MB, 20% (#225)"

- README.md
- cmd/upterm/command/host.go
- docs/upterm_host.md
- etc/completion/upterm.bash_completion.sh
- etc/man/man1/upterm-host.1
- host/authorizedkeys.go
A German non-profit hosts [Codeberg](https://codeberg.org), a popular, free Forgejo instance for a Git code forge with public keys from users.
> Codeberg user authorized key support

- .github/workflows/docker.yaml
- Dockerfile.uptermd
- fly.toml
https://github.com/owenthereal/upterm/pull/261 uses minimum image, but it overrides entrypoint with `uptrend-fly.`
This fixes https://github.com/owenthereal/upterm/issues/262.
> Don't override Dockerfile entrypoint with `uptermd-fly`

- server/sshrouting.go
When using encrypted ssh keys, ssh-agent or an external authenticator (e.g. yubikey), there might be an time interval in which the user has to perform a manual action (typing ssh key password, approving the agent connection, physically touching the yubikey), which will take longer than the 3s timeout that is in place, causing the
connection to be closed with no further explanation:
```console
$ ssh <session_id>@uptermd.upterm.dev
Enter passphrase for key '/home/dtrifiro/.ssh/id_ed25519':
Connection closed by 37.16.25.99 port 22
```
Increasing the timeout to 60s fixes this issue.
> increaase pipeEstablishingTimeout to 60s

- cmd/gendoc/main.go
- cmd/upterm/command/upgrade.go
- cmd/uptermd/command/root.go
- cmd/uptermd/command/version.go
- go.mod
- go.sum
- host/host.go
- internal/version/version.go
- internal/version/version_test.go
- server/sshd.go
- server/sshrouting.go
Adds version compatibility checking between upterm host clients and uptermd servers to help users identify and troubleshoot version-related issues.
- **Semantic version compatibility checking** - Warns on major version mismatches following semver principles
- **Smart server detection** - Only attempts to parse versions from actual uptermd servers
- **Comprehensive warnings** - Clear messages for version mismatches and unknown/older servers
- **Robust parsing** - Regex-based SSH version extraction supporting complex semantic versions
- **Production-ready** - Graceful fallbacks, proper error handling, comprehensive test coverage
- **Centralized version management** in `internal/version` package
- **SSH handshake integration** - Extracts version from server SSH version string
- **Clean API …
> Add host/server version compatibility checking

- .github/workflows/build-and-release.yaml
GoReleaser needs custom PAT to update homebrew-upterm repository, GITHUB_TOKEN only has permissions for current repository
> Use GH_TOKEN for external repository access

- .goreleaser.yml
Got the following error:
```
Warning: Calling conflicts_with formula: is deprecated! There is no replacement.
Please report this issue to the owenthereal/homebrew-upterm tap (not Homebrew/* repositories):
/opt/homebrew/Library/Taps/owenthereal/homebrew-upterm/Casks/upterm.rb:46
```
> Remove conflict_with

- charts/uptermd/templates/hpa.yaml
- charts/uptermd/templates/ingress.yaml
- charts/uptermd/values.yaml
Addresses issues mentioned in #300
This PR updates the upterm Helm chart to be compatible with modern Kubernetes versions (1.22+) where deprecated API versions have been removed.
- **HPA**: Updated from autoscaling/v2beta2 to autoscaling/v2
- **Ingress**: Updated from networking.k8s.io/v1beta1 to networking.k8s.io/v1
- Added missing path: / and pathType: Prefix for v1 compatibility
- Updated backend service reference format for Ingress v1 API
- Added support for customizable ingress annotations via websocket.ingress.annotations
- Added LoadBalancer service type option (commented out by default)
- Disabled autoscaling by default to avoid compatibility issues on older clusters
These changes resolve the deployment issues on Kubernetes 1.31+ clusters where the old API versions are no longer …
> Fix Helm chart for Kubernetes 1.22+ compatibility

- Dockerfile.uptermd
Revert default Dockerfile.upterm stage to copy uptermd from Docker build
This closes https://github.com/owenthereal/upterm/pull/341 & https://github.com/owenthereal/upterm/pull/340/
> Default dockerfile stage
