- cmd/upterm/command/host.go
- cmd/upterm/command/session.go
- ftests/ftests.go
- ftests/test_host.go
- go.mod
- go.sum
- host/admin.go
- host/host.go
- server/sshd.go
- vendor/github.com/eiannone/keyboard/.gitignore
- vendor/github.com/eiannone/keyboard/AUTHORS
- vendor/github.com/eiannone/keyboard/LICENSE
- vendor/github.com/eiannone/keyboard/README.md
- vendor/github.com/eiannone/keyboard/keyboard.go
- vendor/github.com/eiannone/keyboard/keyboard_common.go
- vendor/github.com/eiannone/keyboard/keyboard_windows.go
- vendor/github.com/eiannone/keyboard/syscalls.go
- vendor/github.com/eiannone/keyboard/syscalls_linux.go
- vendor/github.com/eiannone/keyboard/terminfo.go
- vendor/modules.txt
Prompt for session info after a successful connection to the `uptermd`, before running the targeted command.
> Prompt for session info in `upterm host`

- README.md
Looks like this was duplicated.
> Remove redundant part of example

- cmd/uptermd/internal/command/root.go
- ftests/ftests.go
- ftests/ftests_test.go
- server/server.go
- server/sshproxy.go
This is not needed with the introduction of sideway routing
> Remove upstream mode

- cmd/upterm/command/host.go
- ftests/host_test.go
- host/host.go
- utils/utils.go
Creates a session ID using a crypto.Rand generator rather than semi-predictable xid
> Secure session id generate

- ftests/client_test.go
- host/internal/server.go
`make vet` is failing: https://travis-ci.org/github/jingweno/upterm/jobs/684808616.
> Fix `make vet`

- cmd/upterm/command/host.go
- ftests/host_test.go
- go.mod
- go.sum
- host/host.go
- utils/utils.go
- vendor/github.com/dchest/uniuri/.travis.yml
- vendor/github.com/dchest/uniuri/COPYING
- vendor/github.com/dchest/uniuri/README.md
- vendor/github.com/dchest/uniuri/uniuri.go
- vendor/modules.txt
After doing a bit more research, I found https://github.com/dchest/uniuri which does what we do with the following extras:
* Bias check: https://github.com/dchest/uniuri/blob/master/uniuri_test.go#L87-L102
* Boundary check: https://github.com/dchest/uniuri/blob/master/uniuri.go#L57-L59
Besides, adding this cleans up our code a bit.
> Introduce a better random string generator

- cmd/upterm/command/host.go
This fixes https://github.com/jingweno/upterm/issues/31.
> Check command for `upterm host`

- io/reader.go
- io/reader_test.go
This fixes https://github.com/jingweno/upterm/issues/32
> Fix ftest data race issue

- host/host.go
- host/host_test.go
This fixes https://github.com/jingweno/upterm/issues/40
> Create known_hosts file if it doesn't exist

- memlistener/memlistener.go
- memlistener/memlistener_test.go
- server/network.go
Localize the global `listeners`
> Refactor memlistener

- host/signer.go
Try reading corresponding public keys for provided private keys and
compare against the ones from ssh agent.
> Fix issue that ssh agent doesn't work

- charts/uptermd/templates/deployment.yaml
- charts/uptermd/templates/ingress.yaml
- charts/uptermd/values.yaml
- host/internal/reversetunnel.go
- terraform/digitalocean/k8s.tf
> Supply hostname to uptermd

- .github/workflows/build.yml
- go.mod
- go.sum
> Bump to 1.16

- .goreleaser.yml
- README.md
Update homebrew Formula to root
> Update homebrew Formula to root

- go.mod
- go.sum
- host/internal/server.go
- server/sshd.go
- vendor/github.com/gliderlabs/ssh/README.md
- vendor/github.com/gliderlabs/ssh/circle.yml
- vendor/github.com/gliderlabs/ssh/context.go
- vendor/github.com/gliderlabs/ssh/options.go
- vendor/github.com/gliderlabs/ssh/server.go
- vendor/github.com/gliderlabs/ssh/session.go
- vendor/github.com/gliderlabs/ssh/ssh.go
- vendor/golang.org/x/sys/unix/mkerrors.sh
- vendor/golang.org/x/sys/unix/syscall_darwin.go
- vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
- vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
- vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
- vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
- vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
- vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
- vendor/golang.org/x/sys/unix/zerrors_linux.go
- vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
- vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
- vendor/modules.txt
Bump `github.com/gliderlabs/ssh`
> Bump `github.com/gliderlabs/ssh`

- cmd/upterm/command/host.go
- docs/upterm_host.md
- etc/completion/upterm.zsh_completion
- etc/man/man1/upterm-host.1
Just some spelling errors I noticed while testing out upterm
> Fixed some spelling errors

- README.md
> Add notes about RSA keys

- cmd/upterm/command/host.go
Support more private key types from `~/.ssh`
> Support more private key types from `~/.ssh`

- README.md
- systemd/uptermd.service
> Add hardened systemd service

- go.mod
- go.sum
- vendor/golang.org/x/crypto/ssh/agent/client.go
- vendor/golang.org/x/crypto/ssh/agent/keyring.go
- vendor/golang.org/x/crypto/ssh/certs.go
- vendor/golang.org/x/crypto/ssh/client.go
- vendor/golang.org/x/crypto/ssh/client_auth.go
- vendor/golang.org/x/crypto/ssh/common.go
- vendor/golang.org/x/crypto/ssh/handshake.go
- vendor/golang.org/x/crypto/ssh/kex.go
- vendor/golang.org/x/crypto/ssh/keys.go
- vendor/golang.org/x/crypto/ssh/messages.go
- vendor/golang.org/x/crypto/ssh/server.go
- vendor/golang.org/x/crypto/ssh/session.go
- vendor/golang.org/x/crypto/ssh/sshpiper.go
- vendor/golang.org/x/crypto/ssh/transport.go
- vendor/modules.txt
This contains partial fixes to the ssh-rsa issue:
* https://github.com/owenthereal/upterm.crypto/commit/1baeb1ce4c0b006eff0f294c47cb7617598dfb3d
* https://github.com/owenthereal/upterm.crypto/commit/5d542ad81a58c89581d596f49d0ba5d435481bcf
Ref: https://github.com/owenthereal/upterm/issues/93
> Pull in latest x/crypto/ssh

- Dockerfile.uptermd
- fly.toml
Adjust Dockerfile.uptermd to deploy to fly.io. `uptermd.upterm.dev` runs on fly.io now!
> Deploy to fly.io

- go.mod
- go.sum
- io/writer.go
- vendor/github.com/creack/pty/pty_openbsd.go
- vendor/modules.txt
- Simplify cache multi writer
- Bump pty
- Cache with []byte instead of bytes.Buffer
> optimize multiwriter

- bin/heroku-install
- terraform/heroku/main.tf
- terraform/heroku/providers.tf
This change updates the terraform and wrapper to work with the current heroku provider.
> works with current heroku provider

- .goreleaser.yml
Change Linux package bin path and add completion scripts & man pages.
This fixes: https://github.com/owenthereal/upterm/issues/247
> Fix Linux package bin path

- go.mod
- go.sum
- host/internal/server.go
- server/sshd.go
- server/sshhandler.go
- utils/utils.go
Replace with charmbracelet/ssh
> Replace with charmbracelet/ssh

- README.md
> Add README for action-upterm

- .goreleaser.yml
- README.md
- cmd/uptermd-fly/main.go
- fly.example.toml
- fly.toml
- server/wsproxy.go
Updates deployment documentation and infrastructure to prioritize Fly.io over Heroku following the discontinuation of Heroku's free tier (issue #342). This PR includes comprehensive improvements to make Fly.io deployment production-ready while simplifying personal deployments.
- **README updates**: Position Fly.io as the primary "cheapest" deployment option
- **Heroku section**: Updated to note free tier discontinuation (Nov 2022) while preserving instructions
- **Clear guidance**: Reference new example configuration for user deployments
- **Health monitoring**: Added `/health` HTTP endpoint to WebSocket proxy
- **Comprehensive health checks**: TCP checks for SSH service, HTTP checks for WebSocket service
- **PROXY protocol v2**: Enable accurate client IP logging through Fly's load …
> Update deployment recommendations: prioritize Fly.io over Heroku
